import type { DueDiligenceCategory, DueDiligenceItem } from '../models';
import { createId } from '../utils/id';

const ITEMS: { category: DueDiligenceCategory; label: string }[] = [
  { category: 'legal', label: 'Certificate of Occupancy' },
  { category: 'legal', label: 'DOB records / building profile' },
  { category: 'legal', label: 'DOB violations' },
  { category: 'legal', label: 'ECB / OATH violations' },
  { category: 'legal', label: 'HPD violations' },
  { category: 'legal', label: 'HPD registration' },
  { category: 'legal', label: 'Property tax status (NYC Finance / DOF)' },
  { category: 'legal', label: 'Zoning and permitted use' },
  { category: 'legal', label: 'Legal unit count' },
  { category: 'legal', label: 'Permits' },
  { category: 'legal', label: 'Open applications' },
  { category: 'legal', label: 'Rent-regulation considerations' },
  { category: 'legal', label: 'Legal basement / cellar occupancy' },
  { category: 'property', label: 'Roof' },
  { category: 'property', label: 'Boiler' },
  { category: 'property', label: 'HVAC' },
  { category: 'property', label: 'Electrical' },
  { category: 'property', label: 'Plumbing' },
  { category: 'property', label: 'Foundation' },
  { category: 'property', label: 'Structure' },
  { category: 'property', label: 'Water intrusion' },
  { category: 'property', label: 'Facade' },
  { category: 'property', label: 'Windows' },
  { category: 'property', label: 'Lead-related considerations' },
  { category: 'property', label: 'Asbestos considerations' },
  { category: 'property', label: 'Mold / moisture' },
  { category: 'property', label: 'Pest issues' },
  { category: 'tenancy', label: 'Rent roll' },
  { category: 'tenancy', label: 'Leases' },
  { category: 'tenancy', label: 'Security deposits' },
  { category: 'tenancy', label: 'Payment history' },
  { category: 'tenancy', label: 'Arrears' },
  { category: 'tenancy', label: 'Lease expirations' },
  { category: 'tenancy', label: 'Tenant concessions' },
  { category: 'tenancy', label: 'Regulatory status of tenancies' },
  { category: 'financial', label: 'Tax bills' },
  { category: 'financial', label: 'Insurance quote' },
  { category: 'financial', label: 'Utility bills' },
  { category: 'financial', label: 'Repair history' },
  { category: 'financial', label: 'Capital improvements' },
  { category: 'financial', label: 'Actual operating expenses' },
  { category: 'transaction', label: 'Title' },
  { category: 'transaction', label: 'Survey' },
  { category: 'transaction', label: 'Inspection' },
  { category: 'transaction', label: 'Appraisal' },
  { category: 'transaction', label: 'Attorney review' },
  { category: 'transaction', label: 'Financing' },
  { category: 'transaction', label: 'Environmental review (where appropriate)' },
  { category: 'transaction', label: 'Liens' },
];

export function defaultDueDiligence(): DueDiligenceItem[] {
  return ITEMS.map((item) => ({
    id: createId('dd'),
    category: item.category,
    label: item.label,
    status: 'not_started',
    notes: '',
    source: '',
    dateChecked: '',
    documentReference: '',
    severity: 'medium',
    owner: '',
    followUp: '',
  }));
}

export const DUE_DILIGENCE_CATEGORY_LABELS: Record<DueDiligenceCategory, string> = {
  legal: 'Legal / Municipal',
  dob: 'DOB',
  hpd: 'HPD',
  oath: 'OATH / ECB',
  zoning: 'Zoning',
  title: 'Title',
  tenancy: 'Tenancy',
  leases: 'Leases',
  financial: 'Financial',
  structural: 'Structural',
  mechanical: 'Mechanical',
  environmental: 'Environmental',
  insurance: 'Insurance',
  financing: 'Financing',
  appraisal: 'Appraisal',
  closing: 'Closing',
  property: 'Property',
  transaction: 'Transaction',
};
